Repository suruthiii/kindheart, pull requests merged in 2024-04, with the labels that each got.

#155 Small modifications to Super Admin Index Page
  app/views/super admin/index.php
Labels: fix

#156 refactor: Generalized methods of User Controller
  app/controllers/Admin.php
  app/controllers/Necessity.php
  app/controllers/Request.php
  app/controllers/SuperAdmin.php
  app/controllers/User.php
  app/views/admin/request.php
  app/views/admin/user.php
  app/views/inc/components/sidenavbar.php
  app/views/superAdmin/admin.php
  app/views/superAdmin/admin/editAdmin.php
  app/views/superAdmin/admin/viewAdmin.php
  app/views/superAdmin/benefaction.php
  app/views/superAdmin/complaint.php
  app/views/superAdmin/index.php
  app/views/superAdmin/necessity.php
  app/views/superAdmin/necessity/monetary.php
  app/views/superAdmin/necessity/physicalGood.php
  app/views/superAdmin/necessity/viewGood.php
  app/views/superAdmin/necessity/viewGoodDonation.php
  app/views/superAdmin/necessity/viewMonetary.php
  app/views/superAdmin/necessity/viewMonetaryDonation.php
  app/views/superAdmin/project.php
  app/views/superAdmin/report.php
  app/views/superAdmin/request.php
  app/views/superAdmin/request/organizationRequest.php
  app/views/superAdmin/request/studentRequest.php
  app/views/superAdmin/scholarship.php
  app/views/superAdmin/successStory.php
  app/views/superAdmin/user.php
  app/views/superAdmin/user/donor.php
  app/views/superAdmin/user/organization.php
  app/views/superAdmin/user/student.php
  app/views/superAdmin/user/viewDonor.php
  app/views/superAdmin/user/viewOrganization.php
  app/views/superAdmin/user/viewStudent.php
  public/css/components/sidenavbar.css
Labels: refactor

#157 feat: Super Admin's data retrieval for Students' List
  app/controllers/User.php
  app/models/UserModel.php
  app/models/organizationModel.php
  app/views/superAdmin/index.php
  app/views/superAdmin/user/organization.php
  app/views/superAdmin/user/student.php
Labels: feat

#158 fix: Updated Super Admin's View Organization Functionality
  app/controllers/User.php
  app/models/UserModel.php
  app/views/superAdmin/user/viewOrganization.php
Labels: fix

#159 feat: Super Admin's View Student Functionality
  app/controllers/User.php
  app/models/UserModel.php
  app/views/superAdmin/user/viewStudent.php
Labels: feat

#160 fix: Super Admin's View Student Functionality
  app/views/superAdmin/user/viewStudent.php
  public/css/admin.css
  public/nic/default-image.jpg
Labels: fix

#161 feat: Super Admin's data retrieval for Donors' List
  app/controllers/User.php
  app/models/UserModel.php
  app/views/superAdmin/user/donor.php
Labels: feat

#163 fix: Modifications to Super Admin's View User Pages
  app/views/superAdmin/user/donor.php
  app/views/superAdmin/user/organization.php
  app/views/superAdmin/user/student.php
  public/css/admin.css
Labels: fix

#164 refactor: Genaralized Organization's Necessity Functionalities
  app/controllers/Necessity.php
  app/controllers/Organization.php
  app/models/NecessityModel.php
  app/models/organizationModel.php
  app/views/organization/addgoodsnecessity.php
  app/views/organization/addmonetarynecessity.php
  app/views/organization/choosethenecessityType.php
  app/views/organization/postedmonetarynecessity.php
  app/views/organization/postedphysicalgoodsnecessity.php
Labels: refactor

#165 feat: Super Admin's and Admin's data retrieval for Necessity Lists
  app/controllers/Necessity.php
  app/controllers/Student.php
  app/models/NecessityModel.php
  app/views/admin/necessity.php
  app/views/admin/necessity/monetary.php
  app/views/admin/necessity/physicalGood.php
  app/views/admin/necessity/viewGood.php
  app/views/admin/necessity/viewMonetary.php
  app/views/organization/addgoodsnecessity.php
  app/views/organization/addmonetarynecessity.php
  app/views/organization/choosethenecessityType.php
  app/views/student/neccessities.php
  app/views/student/necessity/addgoodsnecessity.php
  app/views/student/necessity/addmonetarynecessity.php
  app/views/superAdmin/necessity.php
  app/views/superAdmin/necessity/monetary.php
  app/views/superAdmin/necessity/physicalGood.php
  app/views/superAdmin/necessity/viewGood.php
  app/views/superAdmin/necessity/viewMonetary.php
Labels: feat

#166 refactor: Genaralized Student's Necessity Functionalities
  app/controllers/Benefaction.php
  app/controllers/Necessity.php
  app/controllers/Student.php
  app/models/BenefactionModel.php
  app/models/ProjectModel.php
  app/models/ScholarshipModel.php
  app/models/SuccessStoryModel.php
  app/models/donorModel.php
  app/views/inc/components/sidenavbar.php
  app/views/student/necessities.php
  app/views/student/necessity/addgoodsnecessity.php
  app/views/student/necessity/addmonetarynecessity.php
  app/views/student/necessity/postedmonetarynecessity.php
  app/views/student/necessity/postedphysicalgoodsnecessity.php
Labels: refactor

#168 refactor: Genaralized Donees' Success Story Functionalities
  app/controllers/Admin.php
  app/controllers/Benefaction.php
  app/controllers/Student.php
  app/controllers/SuccessStory.php
  app/controllers/SuperAdmin.php
  app/models/StudentModel.php
  app/models/SuccessStoryModel.php
  app/views/student/editStory.php
  app/views/student/successstory.php
  app/views/student/viewSuccessStory.php
  public/benefactionUploads/IMG-6612d6319a5952.96936620.jpg
  public/benefactionUploads/IMG-6612d6319a7665.65909957.jpg
  public/benefactionUploads/IMG-6612d6319a8750.59800552.png
  public/benefactionUploads/IMG-6612d6319ab093.02558421.png
  public/uploads/IMG-66128ea140e6e0.15655853.jpg
  public/uploads/IMG-66128f1bd8f3e8.68772432.jpg
  public/uploads/IMG-6612c04d7a2051.25807524.jpg
  public/uploads/IMG-6612c298d95015.62951963.jpg
  public/uploads/IMG-6612c7cadc1268.90371954.png
  public/uploads/IMG-6612c7fd6a9995.40668202.jpg
  public/uploads/IMG-6612c84b8c8258.56851920.png
  public/uploads/IMG-6612cbee6231d3.49629590.png
  public/uploads/IMG-6612cc1a9525b0.55998973.jpg
  public/uploads/IMG-6612cea0b98d18.64069785.png
Labels: refactor

#170 feat: Super Admin's data retrieval for Project Main page
  app/controllers/Admin.php
  app/controllers/Request.php
  app/controllers/SuperAdmin.php
  app/models/BenefactionModel.php
  app/models/NecessityModel.php
  app/models/ProjectModel.php
  app/models/ScholarshipModel.php
  app/views/admin/necessity/monetary.php
  app/views/admin/project.php
  app/views/admin/request.php
  app/views/admin/scholarship.php
  app/views/organization/postedmonetarynecessity.php
  app/views/organization/postedphysicalgoodsnecessity.php
  app/views/superAdmin/necessity/monetary.php
  app/views/superAdmin/project.php
  app/views/superAdmin/scholarship.php
  public/css/style.css
Labels: feat

#171 feat: Admin's data retrieval for Project Main page
  app/controllers/Admin.php
  app/views/admin/project.php
Labels: feat

#174 feat: Super Admin's data retrieval for Posted Necessities
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/models/ProjectModel.php
  app/views/superAdmin/necessity/monetary.php
  app/views/superAdmin/necessity/physicalGood.php
Labels: feat

#175 feat: Admin's data retrieval for Posted Necessities
  app/controllers/Necessity.php
  app/views/admin/necessity/monetary.php
  app/views/admin/necessity/physicalGood.php
  app/views/superAdmin/necessity/monetary.php
  app/views/superAdmin/necessity/physicalGood.php
Labels: feat

#176 feat: Super Admin's data retrieval for Posted Scholarships
  app/controllers/SuperAdmin.php
  app/models/ScholarshipModel.php
  app/views/admin/necessity/monetary.php
  app/views/admin/necessity/physicalGood.php
  app/views/superAdmin/scholarship.php
Labels: feat

#177 feat: Admin's data retrieval for Posted Scholarships
  app/controllers/Admin.php
  app/views/admin/scholarship.php
Labels: feat

#178 fix: Necessity Model for data retrieval of Necessity lists for Admin …
  app/models/NecessityModel.php
Labels: fix

#179 refactor: Generalized Request Methods
  app/controllers/Request.php
  app/views/admin/request.php
Labels: refactor

#181 feat: Donee Request List Data Retrieval for Super Admin and Admin
  app/controllers/Request.php
  app/models/NecessityModel.php
  app/models/RequestModel.php
  app/views/admin/necessity/monetary.php
  app/views/admin/necessity/physicalGood.php
  app/views/admin/project.php
  app/views/admin/request/organizationRequest.php
  app/views/admin/request/studentRequest.php
  app/views/admin/request/viewOrganizationRequest.php
  app/views/admin/request/viewStudentRequest.php
  app/views/admin/scholarship.php
  app/views/superAdmin/necessity/monetary.php
  app/views/superAdmin/necessity/physicalGood.php
  app/views/superAdmin/project.php
  app/views/superAdmin/request/organizationRequest.php
  app/views/superAdmin/request/studentRequest.php
  app/views/superAdmin/request/viewOrganizationRequest.php
  app/views/superAdmin/request/viewStudentRequest.php
  app/views/superAdmin/scholarship.php
  public/css/style.css
Labels: feat

#182 fix: Donee Request List Data Retrieval for Super Admin and Admin
  app/models/RequestModel.php
  app/views/superAdmin/request/organizationRequest.php
  app/views/superAdmin/request/studentRequest.php
Labels: fix

#185 Created benefactions card view
  app/controllers/Student.php
  app/controllers/SuccessStory.php
  app/models/BenefactionModel.php
  app/models/SuccessStoryModel.php
  app/views/inc/components/sidenavbar.php
  app/views/student/benefactions.php
  app/views/student/editStory.php
  app/views/student/scholarships.php
  app/views/student/successstory.php
  app/views/student/viewSuccessStory.php
  public/benefactionUploads/IMG-65df3e11e5ee04.21230510.jpg
  public/css/student.css
Labels: feat

#186 feat: Admin's Student, Organization and Donor Lists' Data Retrieval
  app/views/admin/user.php
  app/views/admin/user/donor.php
  app/views/admin/user/organization.php
  app/views/admin/user/student.php
  app/views/admin/user/viewDonorCom.php
  app/views/admin/user/viewDonorInd.php
  app/views/admin/user/viewOrganization.php
  app/views/admin/user/viewStudent.php
Labels: feat

#187 feat: Admin's View Student Functionality
  app/views/admin/user/viewStudent.php
Labels: feat

#188 feat: Admin's View Organization Functionality
  app/views/admin/user/viewOrganization.php
Labels: feat

#189 feat: Admin's View Company(Donor) Functionality
  app/views/admin/user/viewDonorCom.php
Labels: feat

#190 feat: Admin's View Individual(Donor) Functionality
  app/views/admin/user/viewDonorInd.php
Labels: feat

#192 feat: Super Admin's View Donee Registration Request Functionality
  app/controllers/Request.php
  app/models/RequestModel.php
  app/views/superAdmin/request/viewOrganizationRequest.php
  app/views/superAdmin/request/viewStudentRequest.php
  public/css/student.css
Labels: feat

#191 Finished classifying necessities
  app/models/NecessityModel.php
  app/views/organization/addgoodsnecessity.php
  app/views/organization/addmonetarynecessity.php
  public/css/organization.css
  public/img/necessity-icons/books.png
  public/img/necessity-icons/clothings.png
  public/img/necessity-icons/health.png
  public/img/necessity-icons/one time.png
  public/img/necessity-icons/other.png
  public/img/necessity-icons/recurring.png
  public/img/necessity-icons/sports.png
  public/img/necessity-icons/stationary.png
  public/img/necessity-icons/transport.png
Labels: feat

#193 benefaction view created
  .gitignore
  app/controllers/Benefaction.php
  app/controllers/Student.php
  app/models/BenefactionModel.php
  app/views/student/benefactions.php
  app/views/student/benefactionview.php
  public/.DS_Store
  public/benefactionUploads/IMG-661790463ee4c0.93042652.jpg
  public/benefactionUploads/IMG-661790463f6171.00693197.jpg
  public/benefactionUploads/IMG-661792e215a267.56021741.jpg
  public/benefactionUploads/IMG-661792e2166aa6.09626410.jpg
  public/css/student.css
Labels: feat

#194 feat: Admin's View Student Registration Request Functionality
  app/views/admin/request/viewStudentRequest.php
Labels: feat

#195 feat: Admin's View Organization Registration Request Functionality
  app/views/admin/request/viewOrganizationRequest.php
Labels: feat

#196 fix: View Donee Registration Request Functionality
  app/views/admin/request/viewOrganizationRequest.php
  app/views/admin/request/viewStudentRequest.php
  app/views/superAdmin/request/viewOrganizationRequest.php
  app/views/superAdmin/request/viewStudentRequest.php
Labels: fix

#197 add monetary necessity complete all the changes
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/views/organization/addgoodsnecessity.php
  app/views/organization/addmonetarynecessity.php
  app/views/organization/postedmonetarynecessity.php
  app/views/organization/postedphysicalgoodsnecessity.php
  public/css/organization.css
Labels: feat

#198 feat: Unassign Admin Functionality for Donee Registration Requests
  app/controllers/Request.php
  app/controllers/User.php
  app/models/RequestModel.php
  app/views/admin/request/studentRequest.php
  app/views/superAdmin/request/studentRequest.php
Labels: feat

#199 feat: Unassign Admin for Super Admin's Organization Registration Requ…
  app/views/superAdmin/request/organizationRequest.php
  app/views/superAdmin/request/viewOrganizationRequest.php
Labels: feat

#200 feat: Unassign Admin for Admin's Student Registration Requests
  app/views/admin/request/studentRequest.php
Labels: feat

#201 feat: Unassign Admin for Admin's Organizaition Registration Requests
  app/views/admin/request/organizationRequest.php
Labels: feat

#202 feat: Assign Me Functionality for Admin's Donee Registration Requests
  app/controllers/Request.php
  app/models/RequestModel.php
Labels: feat

#203 feat: Assign Me for Admin's Student Registration Requests
  app/views/admin/request/studentRequest.php
Labels: feat

#204 feat: Assign Me for Admin's Organization Registration Requests
  app/views/admin/request/organizationRequest.php
Labels: feat

#205 set the Icons to goods necessities and add necessity item to add good…
  app/controllers/Necessity.php
  app/views/organization/addmonetarynecessity.php
  app/views/organization/postedphysicalgoodsnecessity.php
Labels: feat

#208 feat: Super Admin's Manage Monetary Necessity Page
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/views/superAdmin/necessity/manageGood.php
  app/views/superAdmin/necessity/manageMonetary.php
  app/views/superAdmin/necessity/monetary.php
  public/css/admin.css
  public/css/style.css
Labels: feat

#209 feat: Super Admin's Manage Good Necessity Page
  app/controllers/Necessity.php
  app/views/superAdmin/necessity/manageGood.php
  app/views/superAdmin/necessity/physicalGood.php
Labels: feat

#210 feat: Admin's Manage Monetary Necessity Page
  app/views/admin/necessity/manageGood.php
  app/views/admin/necessity/manageMonetary.php
  app/views/admin/necessity/monetary.php
Labels: feat

#211 feat: Admin's Manage Good Necessity Page
  app/views/admin/necessity/manageGood.php
  app/views/admin/necessity/physicalGood.php
Labels: feat

#212 feat: Admin's Manage Project Page
  app/controllers/Project.php
  app/views/admin/benefaction/manageBenefaction.php
  app/views/admin/project.php
  app/views/admin/project/manageProject.php
  app/views/admin/scholarship/manageScholarship.php
  app/views/superAdmin/benefaction/manageBenefaction.php
  app/views/superAdmin/project/manageProject.php
  app/views/superAdmin/scholarship/manageScholarship.php
Labels: feat

#213 feat: Super Admin's Manage Project Page
  app/views/superAdmin/project.php
  app/views/superAdmin/project/manageProject.php
Labels: feat

#214 feat: Super Admin's Manage Scholarship Page
  app/controllers/Project.php
  app/controllers/Scholarship.php
  app/views/superAdmin/scholarship.php
  app/views/superAdmin/scholarship/manageScholarship.php
Labels: feat

#215 feat: Admin's Manage Scholarship Page
  app/views/admin/scholarship.php
  app/views/admin/scholarship/manageScholarship.php
Labels: feat

#216 view necessity page begining
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/views/organization/necessity/viewOrganizationPendingMonetarynecessity.php
  app/views/organization/postedmonetarynecessity.php
  app/views/organization/postedphysicalgoodsnecessity.php
  public/css/organization.css
Labels: feat

#217 benefaction view completed
  app/controllers/Student.php
  app/models/BenefactionModel.php
  app/views/student/ApplyForBenefaction.php
  app/views/student/benefactions.php
  app/views/student/benefactionview.php
  app/views/student/viewSuccessStory.php
  public/.DS_Store
  public/benefactionUploads/IMG-661922b7cfafa2.96427797.jpg
  public/benefactionUploads/IMG-661922b7cfe5d0.12449610.jpg
  public/benefactionUploads/IMG-661922b7cfe9a0.91924406.jpg
  public/benefactionUploads/IMG-661922b7cfed28.68875740.jpg
  public/benefactionUploads/IMG-66194076271223.72683805.jpg
  public/css/student.css
Labels: feat

#218 Dithmeena
  app/views/donor/donorAddBenefactions.php
  public/css/donor.css
Labels: feat

#219 view model and controller for posted pending necessity view
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/views/organization/addmonetarynecessity.php
  app/views/organization/necessity/viewOrganizationPendingMonetarynecessity.php
  app/views/organization/postedmonetarynecessity.php
Labels: feat

#221 fix: Changes to Super Admin's Manage Monetary Necessity Page
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/views/superAdmin/necessity/manageMonetary.php
  public/css/admin.css
Labels: fix

#222 fix: Changes to Super Admin's Donee Registration Request Pages
  app/controllers/Request.php
  app/views/superAdmin/request/organizationRequest.php
  app/views/superAdmin/request/studentRequest.php
  app/views/superAdmin/request/viewAssignedOrganizationRequest.php
  app/views/superAdmin/request/viewAssignedStudentRequest.php
  app/views/superAdmin/request/viewUnassignedOrganizationRequest.php
  app/views/superAdmin/request/viewUnassignedStudentRequest.php
Labels: fix

#223 fix: Changes to Admin's Donee Registration Request Pages
  app/views/admin/request/organizationRequest.php
  app/views/admin/request/studentRequest.php
  app/views/admin/request/viewAssignedOrganizationRequest.php
  app/views/admin/request/viewAssignedStudentRequest.php
  app/views/admin/request/viewUnassignedOrganizationRequest.php
  app/views/admin/request/viewUnassignedStudentRequest.php
Labels: fix

#224 feat: Admin's Accept Donee Functionality
  app/controllers/Request.php
  app/models/RequestModel.php
  app/views/admin/request/viewAssignedOrganizationRequest.php
  app/views/admin/request/viewAssignedStudentRequest.php
Labels: feat

#225 feat: Admin's Reject Donee Functionality
  app/controllers/Request.php
  app/models/RequestModel.php
  app/views/admin/request/viewAssignedOrganizationRequest.php
  app/views/admin/request/viewAssignedStudentRequest.php
Labels: feat

#226 feat: Super Admin's All Complaints List View
  app/controllers/Complaint.php
  app/controllers/SuperAdmin.php
  app/models/ComplaintModel.php
  app/views/admin/complaint.php
  app/views/superAdmin/complaint.php
Labels: feat

#227 feat: Super Admin's Unassign Admin Functionality
  app/controllers/Complaint.php
  app/models/ComplaintModel.php
  app/views/superAdmin/complaint.php
Labels: feat

#228 feat: Admin's All Complaints List View
  app/controllers/Admin.php
  app/models/ComplaintModel.php
  app/views/admin/complaint.php
Labels: feat

#229 feat: Admin's Unassign Admin Functionality
  app/controllers/Complaint.php
  app/models/ComplaintModel.php
  app/views/admin/complaint.php
Labels: feat

#230 feat: Admin's Assign Me Functionality
  app/controllers/Complaint.php
  app/views/admin/complaint.php
Labels: feat

#231 do small changes in existing functions
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/views/organization/necessity/viewOrganizationCompletedMonetarynecessity.php
  app/views/organization/necessity/viewOrganizationPendingMonetarynecessity.php
  public/css/organization.css
Labels: fix

#232 feat: Super Admin's View Unassigned Complaint
  app/controllers/Complaint.php
  app/models/ComplaintModel.php
  app/views/admin/complaint.php
  app/views/admin/complaint/viewAssignedComplaint.php
  app/views/admin/complaint/viewUnassignedComplaint.php
  app/views/superAdmin/complaint.php
  app/views/superAdmin/complaint/viewAssignedComplaint.php
  app/views/superAdmin/complaint/viewUnassignedComplaint.php
Labels: feat

#233 fix: Registration Request Handling
  app/controllers/Request.php
  app/models/RequestModel.php
  app/views/superAdmin/request/viewAssignedOrganizationRequest.php
  app/views/superAdmin/request/viewAssignedStudentRequest.php
Labels: fix

#234 redirect viewpending and viewCompleted functions only for admin and s…
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/views/organization/necessity/viewOrganizationCompletedMonetarynecessity.php
  app/views/organization/necessity/viewOrganizationPendingMonetarynecessity.php
  app/views/organization/postedmonetarynecessity.php
  public/css/organization.css
Labels: fix

#235 update monetary necessity controller
  app/controllers/Necessity.php
  app/views/organization/addgoodsnecessity.php
  app/views/organization/addmonetarynecessity.php
  app/views/organization/necessity/editpostedmonetarynecessity.php
  public/benefactionUploads/IMG-661c795a972da6.06755290.jpg
  public/benefactionUploads/IMG-661c795a98bd07.35506630.jpg
Labels: feat

#236 feat: Retrieving Admin, Request and Complaint counts For Super Admin …
  app/controllers/SuperAdmin.php
  app/models/UserModel.php
  app/views/superAdmin/index.php
Labels: feat

#237 fix: Making small modifications to Admin Controller
  app/controllers/Admin.php
Labels: fix

#238 feat: Retrieving Request and Complaint counts For Admin Dashboard
  app/views/admin/index.php
Labels: feat

#242 feat: Super Admin's Manage Necessity View
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/views/superAdmin/necessity/manageMonetary.php
  app/views/superAdmin/necessity/monetary.php
  public/img/sidenav-icons/achievement.png
  public/img/sidenav-icons/admin.png
  public/img/sidenav-icons/analytics.png
  public/img/sidenav-icons/box.png
  public/img/sidenav-icons/complain.png
  public/img/sidenav-icons/earn.png
  public/img/sidenav-icons/give.png
  public/img/sidenav-icons/home.png
  public/img/sidenav-icons/logout.png
  public/img/sidenav-icons/received.png
  public/img/sidenav-icons/registration.png
  public/img/sidenav-icons/user.png
Labels: feat

#243 posted project page begining
  app/controllers/Project.php
  app/views/inc/components/sidenavbar.php
  app/views/organization/project/postedprojects.php
Labels: feat

#244 applied benefaction cards
  app/controllers/Benefaction.php
  app/controllers/Student.php
  app/models/BenefactionModel.php
  app/views/student/ApplyForBenefaction.php
  app/views/student/benefactions.php
  app/views/student/benefactionview.php
  kindheart_db.sql
  public/.DS_Store
  public/benefactionUploads/IMG-661a60e3aef520.70257865.jpg
  public/benefactionUploads/IMG-661a60f5aeb697.07092503.jpg
  public/benefactionUploads/IMG-661a60f5af1609.67417747.jpg
  public/css/student.css
Labels: feat

#246 fix: Admin's Dashboard Cards
  app/controllers/Admin.php
  app/models/UserModel.php
Labels: fix

#245 posted project ongoing and completed table view
  app/controllers/Project.php
  app/models/ProjectModel.php
  app/views/organization/project/postedprojects.php
Labels: feat

#247 feat: Super Admin's Manage Necessity View for Confirmed Monetary Nece…
  app/views/superAdmin/necessity/monetary.php
Labels: feat

#248 feat: Super Admin's Manage Necessity View for Ongoing Monetary Necess…
  app/views/superAdmin/necessity/monetary.php
Labels: feat

#249 add project view begining
  app/controllers/Project.php
  app/views/organization/addmonetarynecessity.php
  app/views/organization/project/addprojects.php
  app/views/organization/project/postedprojects.php
  public/css/organization.css
Labels: feat

#250 feat: Super Admin's Manage Necessity Add Comment Functionality
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/views/superAdmin/necessity/manageMonetary.php
  public/css/admin.css
Labels: feat

#251 fix: Super Admin's Manage Necessity Add Comment Functionality
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/views/superAdmin/necessity/manageMonetary.php
  public/css/admin.css
Labels: fix

#252 feat: Super Admin's Manage Necessity View Comment History Functionality
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/views/superAdmin/necessity/manageMonetary.php
Labels: feat

#253 feat: Super Admin's View Monetary Necessity Functionality
  app/controllers/Necessity.php
  app/models/UserModel.php
  app/views/superAdmin/necessity/monetary.php
  app/views/superAdmin/necessity/viewMonetary.php
Labels: feat

#254 add project add more column
  app/views/organization/project/addprojects.php
  public/css/organization.css
Labels: feat

#257 feat: Super Admin's Manage Physical Good Necessity Functionality
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/views/superAdmin/necessity/manageGood.php
  app/views/superAdmin/necessity/physicalGood.php
Labels: feat

#258 feat: Super Admin's View Physical Good Necessity Functionality
  app/controllers/Necessity.php
  app/views/superAdmin/necessity/physicalGood.php
  app/views/superAdmin/necessity/viewGood.php
Labels: feat

#260 feat: Admin's View Monetary Necessity Functionality
  app/views/admin/necessity/viewMonetary.php
Labels: feat

#261 feat: Admin's Manage Physical Good Necessity Functionality
  app/views/admin/necessity/manageGood.php
  app/views/admin/necessity/physicalGood.php
Labels: feat

#262 feat: Admin's Physical Good Necessity Functionality
  app/views/admin/necessity/viewGood.php
Labels: feat

#264 feat: Admin's Manage Project Functionality
  app/controllers/Project.php
  app/models/NecessityModel.php
  app/models/ProjectModel.php
  app/views/admin/benefaction/viewBenefaction.php
  app/views/admin/project.php
  app/views/admin/project/manageProject.php
  app/views/admin/project/viewProject.php
  app/views/admin/scholarship/viewScholarship.php
  app/views/superAdmin/benefaction/viewBenefaction.php
  app/views/superAdmin/project/viewProject.php
  app/views/superAdmin/scholarship/viewScholarship.php
Labels: feat

#265 feat: Admin's View Project Functionality
  app/controllers/Project.php
  app/models/ProjectModel.php
  app/views/admin/project.php
  app/views/admin/project/viewProject.php
Labels: feat

#266 feat: Super Admin's Manage Project Functionality
  app/views/superAdmin/project.php
  app/views/superAdmin/project/manageProject.php
Labels: feat

#267 feat: Super Admin's View Project Functionality
  app/controllers/Project.php
  app/views/superAdmin/project/viewProject.php
Labels: feat

#269 feat: Super Admin's Manage Scholarship Functionality
  app/controllers/Necessity.php
  app/controllers/Scholarship.php
  app/models/ScholarshipModel.php
  app/views/admin/project/viewProject.php
  app/views/superAdmin/scholarship.php
  app/views/superAdmin/scholarship/manageScholarship.php
Labels: feat

#268 add project add new description to milestones
  app/views/organization/project/addprojects.php
  public/css/organization.css
Labels: feat

#271 feat: Super Admin's View Success Story List Functionality
  app/controllers/Scholarship.php
  app/views/student/successstory.php
  app/views/superAdmin/successStory.php
Labels: feat

#272 feat: Admin's Manage Scholarship Functionality
  app/views/admin/scholarship.php
  app/views/admin/scholarship/manageScholarship.php
  app/views/superAdmin/scholarship.php
Labels: feat

#273 feat: Admin's View Scholarship Functionality
  app/views/admin/scholarship/viewScholarship.php
Labels: feat

#274 changes in add project view
  app/views/organization/project/addprojects.php
  public/css/organization.css
  public/img/up-loading.png
Labels: fix

#275 404 page
  app/controllers/Benefaction.php
  app/controllers/Student.php
  app/models/BenefactionModel.php
  app/views/404.php
  app/views/student/ApplyForBenefaction.php
  public/.DS_Store
  public/benefactionUploads/IMG-66237e98e71846.47409944.jpg
  public/benefactionUploads/IMG-66237e98e8b9e8.74888576.jpg
  public/benefactionUploads/IMG-662380b087a7d2.51558156.jpg
  public/benefactionUploads/IMG-662380b0890701.56641528.jpg
  public/css/student.css
  public/css/style.css
  public/img/404image.png
Labels: feat

#276 Add Project front changes for now completed
  app/views/organization/project/addprojects.php
  public/css/organization.css
Labels: feat

#277 fix: Super Admin's View Complaint
  app/controllers/Complaint.php
  app/models/ComplaintModel.php
  app/views/superAdmin/complaint.php
  app/views/superAdmin/complaint/viewComplaint.php
  app/views/superAdmin/complaint/viewUnassignedComplaint.php
  public/css/style.css
  public/img/sidenav-icons/achievement.png
  public/img/sidenav-icons/admin.png
  public/img/sidenav-icons/analytics.png
  public/img/sidenav-icons/box.png
  public/img/sidenav-icons/complain.png
  public/img/sidenav-icons/earn.png
  public/img/sidenav-icons/give.png
  public/img/sidenav-icons/home.png
  public/img/sidenav-icons/logout.png
  public/img/sidenav-icons/received.png
  public/img/sidenav-icons/registration.png
  public/img/sidenav-icons/user.png
Labels: fix

#278 feat: Super Admin's Assign Admins For Complaints
  app/controllers/Complaint.php
  app/controllers/SuperAdmin.php
  app/models/ComplaintModel.php
  app/views/superAdmin/complaint.php
  app/views/superAdmin/complaint/viewComplaint.php
  public/css/style.css
Labels: feat

#279 View Benefaction Request
  app/controllers/Benefaction.php
  app/controllers/Scholarship.php
  app/models/ScholarshipModel.php
  app/models/donorModel.php
  app/views/donor/editPostedScholarships.php
  app/views/donor/index.php
  app/views/donor/temporyStudentProfile.php
  app/views/donor/viewBenefactionRequest.php
  app/views/donor/viewPostedBenefactions.php
  app/views/donor/viewPostedScholarships.php
  public/css/donor.css
  public/img/check.png
  public/img/close.png
Labels: feat

#280 feat: Super Admin's View Past Complaints Functionality
  app/controllers/Complaint.php
  app/models/ComplaintModel.php
  app/views/superAdmin/complaint/viewComplaint.php
Labels: feat

#282 feat: Super Admin's View Complainee and Complainer Profiles Functiona…
  app/controllers/Complaint.php
  app/models/ComplaintModel.php
  app/views/superAdmin/complaint/viewComplaint.php
  app/views/superAdmin/complaint/viewDonorComProfile.php
  app/views/superAdmin/complaint/viewDonorIndProfile.php
  app/views/superAdmin/complaint/viewOrganizationProfile.php
  app/views/superAdmin/complaint/viewStudentProfile.php
Labels: feat

#281 add project controller
  app/controllers/Project.php
  app/views/organization/project/addprojects.php
Labels: feat

#285 feat: Admin's View Complainer and Complainee Profiles
  app/controllers/Complaint.php
  app/views/admin/complaint/viewComplaint.php
  app/views/admin/complaint/viewDonorComProfile.php
  app/views/admin/complaint/viewDonorIndProfile.php
  app/views/admin/complaint/viewOrganizationProfile.php
  app/views/admin/complaint/viewStudentProfile.php
Labels: feat

#286 feat: Admin's Assign Admin for Registration Requests Functionality
  app/controllers/Request.php
  app/models/RequestModel.php
  app/views/superAdmin/request/organizationRequest.php
  app/views/superAdmin/request/studentRequest.php
  app/views/superAdmin/request/viewUnassignedOrganizationRequest.php
  app/views/superAdmin/request/viewUnassignedStudentRequest.php
Labels: feat

#284 Add project model
  app/controllers/Necessity.php
  app/controllers/Project.php
  app/models/ProjectModel.php
  app/views/organization/postedmonetarynecessity.php
  app/views/organization/postedphysicalgoodsnecessity.php
  app/views/organization/project/postedprojects.php
  public/css/organization.css
  public/projectmilestoneuploadedimages/1697537527372_dsc_0410copy.jpg
  public/projectmilestoneuploadedimages/HA01-F-Side.jpg
  public/projectmilestoneuploadedimages/Open-Source-Databases.png
  public/projectmilestoneuploadedimages/_627bee21-ee29-4221-9aec-d752361feb13.jpeg
  public/projectmilestoneuploadedimages/_6a0b11e2-366e-4466-afc7-d04e1c6754b4.jpeg
  public/projectmilestoneuploadedimages/download (1).jpeg
  public/projectmilestoneuploadedimages/download (2).jpeg
  public/projectmilestoneuploadedimages/download (3).jpeg
  public/projectmilestoneuploadedimages/download (4).jpeg
  public/projectmilestoneuploadedimages/work-from-home-pros-and-cons.png
Labels: feat

#289 Total number of donors donate for monetary necessity
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/views/organization/postedmonetarynecessity.php
Labels: feat

#291 feat: Super Admin's View Donee Profile Functionality for Necessities
  app/views/admin/necessity/viewGoodDonation.php
  app/views/admin/necessity/viewMonetaryDonation.php
  app/views/superAdmin/necessity/viewGood.php
  app/views/superAdmin/necessity/viewGoodDonation.php
  app/views/superAdmin/necessity/viewGoodOrganizationProfile.php
  app/views/superAdmin/necessity/viewGoodStudentProfile.php
  app/views/superAdmin/necessity/viewMonetary.php
  app/views/superAdmin/necessity/viewMonetaryDonation.php
  app/views/superAdmin/necessity/viewMonetaryOrganizationProfile.php
  app/views/superAdmin/necessity/viewMonetaryStudentProfile.php
Labels: feat

#293 Start to create posted project view front end
  app/controllers/Necessity.php
  app/controllers/Project.php
  app/models/ProjectModel.php
  app/views/organization/project/addprojects.php
  app/views/organization/project/postedprojects.php
  app/views/organization/project/viewPendingprojectsdetails.php
  public/css/organization.css
  public/projectmilestoneuploadedimages/0_w0336y3gGR_Z0Rkq.png
  public/projectmilestoneuploadedimages/1_yZk7AEujQpMVXPjBZ51ecjhjskhferjghegw.jpg
  public/projectmilestoneuploadedimages/1_yZk7AEujQpMVXPjBZ51ecw.jpg
  public/projectmilestoneuploadedimages/Distributed-Databajkbdhbdjhvwejfhwse-System.jpg
  public/projectmilestoneuploadedimages/_97ec9984-ca77-4a91-84a9-d93c3d67e95e.jpeg
  public/projectmilestoneuploadedimages/_9d435c7d-4a14-41cc-94bf-254bc3410a69.jpg
  public/projectmilestoneuploadedimages/_af2e2f5e-2ff8-4799-bc53-74c5abcaff40.jpeg
Labels: feat

#295 feat: Admin's View Donee Profile Functionality for Projects
  app/views/admin/project/viewOrganizationProfile.php
  app/views/admin/project/viewProject.php
Labels: feat

#297 feat: Super Admin's View Donor Profile Functionality for Scholarships
  app/views/admin/necessity/viewGoodOrganizationProfile.php
  app/views/admin/necessity/viewMonetaryOrganizationProfile.php
  app/views/superAdmin/necessity/viewGoodOrganizationProfile.php
  app/views/superAdmin/necessity/viewMonetaryOrganizationProfile.php
  app/views/superAdmin/scholarship/viewDonorComProfile.php
  app/views/superAdmin/scholarship/viewDonorIndProfile.php
  app/views/superAdmin/scholarship/viewScholarship.php
Labels: feat

#298 feat: Delete Necessity Functionality for Admin and Super Admin
  app/controllers/Necessity.php
  app/views/admin/necessity/manageGood.php
  app/views/admin/necessity/manageMonetary.php
  app/views/superAdmin/necessity/manageGood.php
  app/views/superAdmin/necessity/manageMonetary.php
Labels: feat

#299 feat: Delete Project Functionality for Admin and Super Admin
  app/controllers/Project.php
  app/views/admin/project/manageProject.php
  app/views/superAdmin/project/manageProject.php
Labels: feat

#301 Dithmeena
  app/controllers/Benefaction.php
  app/controllers/Scholarship.php
  app/models/ScholarshipModel.php
  app/models/donorModel.php
  app/views/donor/postedBenefactions.php
  app/views/donor/tempViewBenfactionRequestOngoin.php
  app/views/donor/tempViewPostedBen.php
  app/views/donor/viewBenefactionRequestCompleted.php
  app/views/donor/viewBenefactionRequestOngoing.php
  app/views/donor/viewBenefactionRequestPending.php
  app/views/donor/viewPostedBenefactionsCompleted.php
  app/views/donor/viewPostedBenefactionsPending.php
  app/views/donor/viewPostedBenefactionsRequested.php
  app/views/donor/viewPostedScholarships.php
  app/views/donor/viewScholarshipApplication.php
  public/css/donor.css
Labels: feat

#303 feat: Notification Count Functionality for Super Admin
  app/controllers/SuperAdmin.php
  app/models/NotificationModel.php
  app/views/inc/components/topnavbar.php
  app/views/superAdmin/admin.php
  public/css/components/topnavbar.css
Labels: feat

#302 ongoing posted project front end view
  app/controllers/Project.php
  app/views/organization/project/viewPendingprojectsdetails.php
  public/css/organization.css
Labels: feat

#306 Dithmeena - Benefaction Model to benfecation model change
  app/controllers/Benefaction.php
  app/views/donor/editPostedBenefactions.php
Labels: feat

#307 feat: delete notifications
  app/controllers/Admin.php
  app/controllers/Benefaction.php
  app/controllers/Complaint.php
  app/controllers/Donor.php
  app/controllers/Necessity.php
  app/controllers/Notification.php
  app/controllers/Organization.php
  app/controllers/Project.php
  app/controllers/Request.php
  app/controllers/Scholarship.php
  app/controllers/Student.php
  app/controllers/SuccessStory.php
  app/controllers/SuperAdmin.php
  app/controllers/User.php
  app/models/NecessityModel.php
  app/models/NotificationModel.php
  app/views/inc/components/topnavbar.php
  app/views/superAdmin/necessity/manageMonetary.php
  app/views/superAdmin/necessity/viewMonetary.php
  public/css/components/topnavbar.css
Labels: feat

#309 Dithmeena - Student Registration Account Creation New
  app/controllers/Users.php
  app/views/donor/postedBenefactions.php
  app/views/users/emailVerifyOTP.php
  app/views/users/login.php
  app/views/users/registerLanding.php
  app/views/users/studentRegistration.php
  app/views/users/studentRegistration/studentAcountCreationPage1.php
  app/views/users/studentRegistration/studentAcountCreationPage2.php
  app/views/users/studentRegistration/studentAcountCreationPage3.php
  public/css/registerAndLogin.css
  public/css/registration_Login.css
Labels: feat

#310 Add necessity controller and view updated according to the database
  app/controllers/Necessity.php
  app/controllers/Project.php
  app/models/NecessityModel.php
  app/views/organization/addmonetarynecessity.php
  app/views/organization/postedmonetarynecessity.php
  app/views/organization/postedphysicalgoodsnecessity.php
  app/views/organization/project/postedprojects.php
  app/views/organization/project/viewPendingprojectsdetails.php
  public/projectmilestoneuploadedimages/Gmail-Undo-Redo.jpg
  public/projectmilestoneuploadedimages/OIP.jpeg
  public/projectmilestoneuploadedimages/Top-5-Free-Cross-Platform-and-Open-Source-Databasehsjgahgfjhagfjagfewfj-System-in-2020.jpg
  public/projectmilestoneuploadedimages/download.jpeg
Labels: feat

#311 Correct necessity view errors according to updated database
  app/models/NecessityModel.php
  app/views/organization/necessity/viewOrganizationCompletedMonetarynecessity.php
  app/views/organization/necessity/viewOrganizationPendingMonetarynecessity.php
Labels: fix

#312 Add alert for delete buttons in view pages
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/views/organization/index.php
  app/views/organization/necessity/viewOrganizationCompletedMonetarynecessity.php
  app/views/organization/necessity/viewOrganizationCompletedphysicalgoodsnecessity.php
  app/views/organization/necessity/viewOrganizationPendingMonetarynecessity.php
  app/views/organization/necessity/viewOrganizationPendingPhysicalGoodsnecessity.php
  app/views/organization/postedmonetarynecessity.php
  app/views/organization/postedphysicalgoodsnecessity.php
  app/views/organization/project/postedprojects.php
  app/views/organization/project/viewCompletedprojectsdetails.php
  app/views/organization/project/viewPendingprojectsdetails.php
  public/css/organization.css
Labels: feat

#314 Dithmeena Student Account Creation
  app/controllers/Users.php
  app/models/UserModel.php
  app/views/users/studentCreatingProfile1.php
  app/views/users/studentRegistration/studentAcountCreationPage1.php
  app/views/users/studentRegistration/studentAcountCreationPage2.php
  app/views/users/studentRegistration/studentProfileCreation2.php
  app/views/users/studentRegistration/studentProfileCreation3.php
  app/views/users/studentRegistration/studentProfileCreation4.php
  app/views/users/studentRegistration/studentProfileCreation5.php
  app/views/users/studentRegistration/studentProfileCreation6.php
  app/views/users/studentRegistration/studentProfileCreation7.php
  app/views/users/studentRegistration/studentProfileCreation8.php
  public/css/registration_Login.css
Labels: feat

#316 Edit/Update Recurring necessity Completed
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/views/organization/necessity/editpostedrecurringmonetarynecessity.php
Labels: feat

#319 Edit recurring necessities completed from view page
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/views/organization/necessity/editpostedonetimemonetarynecessity.php
  app/views/organization/necessity/viewOrganizationPendingMonetarynecessity.php
  app/views/organization/project/postedprojects.php
  app/views/organization/project/viewCompletedprojectsdetails.php
  app/views/organization/project/viewPendingprojectsdetails.php
Labels: feat

#320 Backend of Dashboard
  app/controllers/Necessity.php
  app/controllers/Organization.php
  app/controllers/Project.php
  app/models/organizationModel.php
  app/views/organization/index.php
  app/views/organization/project/editpostedProjectsInterface.php
  app/views/organization/project/postedprojects.php
Labels: feat

#321 feat: Email Sending Functionality
  app/models/RequestModel.php
  app/models/UserModel.php
Labels: feat

#322 Edit of physical goods
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/views/organization/necessity/editphysicalgoodsnecessity.php
  app/views/organization/postedphysicalgoodsnecessity.php
  app/views/organization/project/editpostedProjectsInterface.php
Labels: feat

#324 Dashboard changes
  app/controllers/Necessity.php
  app/views/donor/index.php
  app/views/organization/index.php
  app/views/student/index.php
Labels: feat

#326 benefaction view
  app/controllers/Scholarship.php
  app/controllers/Student.php
  app/controllers/Users.php
  app/models/BenefactionModel.php
  app/models/ScholarshipModel.php
  app/models/StudentModel.php
  app/views/inc/components/sidenavbar.php
  app/views/inc/components/topnavbar.php
  app/views/student/AknowledgementComplain.php
  app/views/student/AknowledgementSuccessful.php
  app/views/student/ApplyForBenefaction.php
  app/views/student/ApplyForScholarship.php
  app/views/student/ViewApplyScholarship.php
  app/views/student/benefactions.php
  app/views/student/benefactionview.php
  app/views/student/donorList.php
  app/views/student/donorView.php
  app/views/student/editProfile.php
  app/views/student/editStory.php
  app/views/student/reg forms/studentAccountCreationSuccessful.php
  app/views/student/reg forms/studentCreatingProfile1.php
  app/views/student/reg forms/studentCreatingProfile2.php
  app/views/student/reg forms/studentCreatingProfile3.php
  app/views/student/reg forms/studentCreatingProfile4.php
  app/views/student/reg forms/studentCreatingProfile5.php
  app/views/student/reg forms/studentCreatingProfile6.php
  app/views/student/reg forms/studentCreatingProfile7.php
  app/views/student/reg forms/studentProfileCreationSuccessful.php
  app/views/student/reg forms/studentSetPassword.php
  app/views/student/scholarships.php
  app/views/student/successstory.php
  app/views/student/viewAppliedBenefaction.php
  public/benefactionUploads/IMG-662a0e0c3d2851.23614991.jpg
  public/benefactionUploads/IMG-662a0e0c3dcf23.83653873.jpg
  public/benefactionUploads/IMG-662a683d03ceb3.91290802.jpeg
  public/benefactionUploads/IMG-662a683d044bf1.67344128.jpg
  public/benefactionUploads/IMG-662a6ada313a56.03230645.jpg
  public/benefactionUploads/IMG-662a6ada31a2e5.70340348.jpg
  public/benefactionUploads/IMG-662b1f6482e2a1.05342876.jpg
  public/benefactionUploads/IMG-662b1f64836a61.57904465.jpg
  public/css/student.css
  public/css/style.css
  public/img/handshake.svg
  public/img/logout.svg
  public/img/settings.svg
Labels: feat

#327 benefaction view
  app/views/inc/components/sidenavbar.php
Labels: feat

#328 Donor who donated one-time
  app/models/NecessityModel.php
  app/views/organization/necessity/editpostedonetimemonetarynecessity.php
  app/views/organization/necessity/viewOrganizationPendingMonetarynecessity.php
Labels: feat

#329 feat: Super Admin's Monetary Necessity Donation List View
  app/controllers/Necessity.php
  app/controllers/Project.php
  app/models/NecessityModel.php
  app/models/ProjectModel.php
  app/models/RequestModel.php
  app/views/superAdmin/necessity/viewDonationDetails.php
  app/views/superAdmin/necessity/viewMonetary.php
  app/views/superAdmin/project/viewMilestoneDetails.php
  app/views/superAdmin/project/viewMilestoneFundDetails.php
  app/views/superAdmin/project/viewProject.php
  public/css/style.css
Labels: feat

#330 fix: edit admin
  app/controllers/SuperAdmin.php
  app/views/superAdmin/admin/editAdmin.php
  public/css/components/topnavbar.css
Labels: feat

#331 Donor who Donated in one-time Necessity Model
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/views/organization/necessity/viewOrganizationPendingMonetarynecessity.php
  app/views/organization/postedmonetarynecessity.php
Labels: feat

#335 Dithmeena Benefaction State Change
  app/controllers/Benefaction.php
  app/models/BenefactionModel.php
  app/views/donor/postedBenefactions.php
  app/views/donor/viewBenefactionRequestAccepted.php
  app/views/donor/viewBenefactionRequestCompleted.php
  app/views/donor/viewPostedBenefactionsPending.php
  public/benefactionUploads/IMG-662c99c7d29cd3.96604774.jpg
  public/benefactionUploads/IMG-662c99f1a4ff95.21516485.jpg
  public/benefactionUploads/IMG-662c9a41112387.81502578.jpg
  public/benefactionUploads/IMG-662ca38d8d6962.27444919.jpg
  public/benefactionUploads/IMG-662ca434a654e2.52761207.jpg
  public/benefactionUploads/IMG-662ca9c4734348.49812408.jpg
  public/benefactionUploads/IMG-662cabe2505819.61936172.jpg
  public/benefactionUploads/IMG-662cb1efe212f5.82329004.png
  public/benefactionUploads/IMG-662cb2b9402955.80375955.jpg
  public/css/donor.css
Labels: feat

#336 Dithmeena Benefaction
  app/controllers/Benefaction.php
  app/models/BenefactionModel.php
  app/views/donor/postedBenefactions.php
  app/views/donor/viewBenefactionRequestAccepted.php
  app/views/donor/viewBenefactionRequestCompleted.php
  app/views/donor/viewBenefactionRequestDeclined.php
  app/views/donor/viewBenefactionRequestOngoing.php
  app/views/donor/viewPostedBenefactionsCompleted.php
  app/views/donor/viewPostedBenefactionsRequested.php
  public/benefactionUploads/IMG-662cb3e68162d7.65131205.jpg
  public/benefactionUploads/IMG-662cb3e6818719.65336511.jpg
  public/benefactionUploads/IMG-662cb578955417.48652847.jpg
  public/benefactionUploads/IMG-662cb578957611.43302334.jpg
  public/benefactionUploads/IMG-662cb64c7d3e48.02970741.jpg
  public/benefactionUploads/IMG-662cb64c7d5f30.82805133.jpg
  public/benefactionUploads/IMG-662cb65e6414e8.41690179.jpg
  public/benefactionUploads/IMG-662cb65e644091.38395858.jpg
  public/benefactionUploads/IMG-662cb6cfb22490.94691417.jpg
  public/benefactionUploads/IMG-662cb6cfb24220.80409865.jpg
  public/benefactionUploads/IMG-662cb6ec7554b4.81715721.jpg
  public/benefactionUploads/IMG-662cb6ec757190.43745380.jpg
  public/benefactionUploads/IMG-662cb6efdce576.72453615.jpg
  public/benefactionUploads/IMG-662cb6efdcfe32.25345352.jpg
  public/benefactionUploads/IMG-662cbcf9d9c315.29345670.png
  public/benefactionUploads/IMG-662cbd10723e79.83757133.png
  public/benefactionUploads/IMG-662cc7af9c33f2.23645864.jpg
  public/benefactionUploads/IMG-662cc7af9c4f81.92048805.png
  public/benefactionUploads/IMG-662cc7ce1396d5.82788436.jpg
  public/benefactionUploads/IMG-662cc7ce13bd38.81328116.png
  public/benefactionUploads/IMG-662cc82fec0658.64442186.jpg
  public/benefactionUploads/IMG-662cc82fec21c2.34486006.png
  public/benefactionUploads/IMG-662cc93500c4e8.02707075.jpg
  public/benefactionUploads/IMG-662cc9350103e8.51655530.png
  public/benefactionUploads/IMG-662cc94eb9de88.13567789.jpg
  public/benefactionUploads/IMG-662cc993c77588.48141960.jpg
  public/benefactionUploads/IMG-662ccc0f81e0e6.44185657.jpg
  public/benefactionUploads/IMG-662ccdb1105391.13803360.jpg
  public/benefactionUploads/IMG-662ccdb1106fd6.52414266.jpg
  public/benefactionUploads/IMG-662cd87a690fd4.46036343.jpg
  public/benefactionUploads/IMG-662cd9522f33b4.25381814.jpg
  public/benefactionUploads/IMG-662cd9ebc90f41.26536723.jpg
  public/benefactionUploads/IMG-662cdaab1af231.44647291.jpg
  public/benefactionUploads/IMG-662cdad613adb0.64786098.jpg
  public/css/donor.css
Labels: feat

#337 fullfilment sates 1 necessities
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/views/organization/postedmonetarynecessity.php
  public/css/organization.css
Labels: feat

#338 student donor profile view compiled
  app/controllers/Student.php
  app/models/StudentModel.php
  app/views/inc/components/sidenavbar.php
  app/views/student/donorList.php
  app/views/student/donorView.php
  app/views/student/editProfile.php
  public/benefactionUploads/IMG-662c966cdf7796.78398348.jpg
  public/benefactionUploads/IMG-662c966ce147a5.47234971.jpg
  public/benefactionUploads/IMG-662c96d9b3c190.71196073.jpg
  public/css/student.css
  public/img/IdividualDP.jpg
  public/img/companyDP.jpg
  public/img/kind heart all white logo.png
Labels: feat

#340 feat: Notification Creation for Manage Necessity
  app/controllers/Necessity.php
Labels: feat

#341 success story first page
  app/controllers/Necessity.php
  app/controllers/Organization.php
  app/controllers/SuccessStory.php
  app/models/NecessityModel.php
  app/views/organization/editStory.php
  app/views/organization/necessity/editpostedrecurringmonetarynecessity.php
  app/views/organization/necessity/viewOrganizationPendingMonetarynecessity.php
  app/views/organization/postedmonetarynecessity.php
  app/views/organization/successstory.php
  app/views/organization/viewStory.php
  app/views/organization/viewSuccessStory.php
Labels: feat

#342 fix: Ban Complainee for Admin
  app/controllers/Admin.php
  app/controllers/Benefaction.php
  app/controllers/Complaint.php
  app/controllers/Project.php
  app/controllers/Scholarship.php
  app/controllers/SuperAdmin.php
  app/models/BenefactionModel.php
  app/models/ComplaintModel.php
  app/models/NecessityModel.php
  app/models/ProjectModel.php
  app/models/ScholarshipModel.php
  app/views/admin/benefaction.php
  app/views/admin/complaint/viewComplaint.php
  app/views/superAdmin/benefaction.php
  app/views/superAdmin/benefaction/viewBenefaction.php
  public/benefactionUploads/IMG-662d348c8becb4.18897010.jpg
  public/benefactionUploads/IMG-662d34a7cb98e8.51877654.png
  public/benefactionUploads/IMG-662d34a7cc24b5.63588950.png
  public/benefactionUploads/IMG-662d34bd1fc7c3.58797668.png
  public/benefactionUploads/IMG-662d34bd2042f3.21169701.png
  public/benefactionUploads/IMG-662d34df29bc39.23428152.png
  public/benefactionUploads/IMG-662d34df2a1783.35353145.png
Labels: feat, fix

#343 posted necessity donor start donate
  app/controllers/Necessity.php
  app/models/NecessityModel.php
  app/views/organization/necessity/viewOrganizationDonationstartMonetarynecessity.php
  app/views/organization/postedmonetarynecessity.php
  public/css/organization.css
Labels: feat

#344 edit profile completed
  app/controllers/Student.php
  app/models/StudentModel.php
  app/views/student/editProfile.php
  public/css/student.css
Labels: feat
